version: "3.3"

services:
  notes-web:
    build:
      context: ..
      dockerfile: Dockerfile
    image: notes-web:1.0
    ports:
      - "8888:8888"
    environment:
      - MYSQL_HOST=mysql-local
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - back-tier
    depends_on:
      - mysql-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8888/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  mysql-local:
    image: mysql:5.7
    ports:
      - "13306:3306"
    volumes:
      - type: bind
        source: ~/data/mysql-docker/mysql-data2/mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - back-tier

networks:
  back-tier: {}