#使用什么样的日志实例 single/rotate/console/custom
driver: rotate
#格式
formatter: text
#设置日志级别
level: info
#日志目录
folder: logs
#日志文件
file: notes.log
#时间格式
date_format:
# 切割相关 数量、大小、最大生存时间、切割时间点，其它可以查看库源码提供的options的withXXX方法
rotate_count:
rotate_size:
max_age:
rotate_time: